version: '2'

services:
  mycoretest:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
